name: Setup Quarto
description: Common steps for installing quarto
runs:
  using: "composite"
  steps:
    - uses: quarto-dev/quarto-actions/setup@v2
    - name: install quarto extensions
      working-directory: ./website/skirolly/
      shell: bash
      run: quarto add --no-prompt https://github.com/qmd-lab/closeread/archive/e3645070dd668004056ae508d2d25d05baca5ad1.zip
