project:
  type: website
  output-dir: ../data/webapp
website:
  title: "OpenSkiStats"
  search: false
  site-url: https://openskistats.org
  favicon: common/snowflake.svg
  navbar:
    left:
      - href: ski-areas/
        text: Ski Areas
      - href: story/
        text: Story
      - href: manuscript/
        text: Manuscript
    right:
      - icon: github
        href: https://github.com/dhimmel/openskistats
  page-footer:
    left:
      This website is released under a [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/).

format:
  html:
    theme: cosmo
    css: common/style.css
    toc: true
    code-fold: true
    include-in-header:
      - common/matomo.html

jupyter: python3
